name: Laravel CI/CD Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy on Server
        run: |
          ssh -o StrictHostKeyChecking=no -p ${{ secrets.SSH_PORT }} \
          ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            
            # আপনার প্রোজেক্টের সঠিক পাথে যান
            cd /home/dhakaglobal/public_html
            
            echo "Pulling latest code..."
            git pull origin main
            
            echo "Deployment successful!"
          EOF